### ISSUE TITLE
Map layout

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#16]
Obviously the dimensions are a bit off, but this is the likely layout that we're going for.

![Marmot Layout](https://user-images.githubusercontent.com/18316906/95346884-2630ef80-0871-11eb-9fea-529de8ff222a.png)

**Comment by noelmurillo15** [comment]
Used cubes to map out this floor plan

**Comment by noelmurillo15** [comment]
Updated MInimap to depict this map layout
