### ISSUE TITLE
Click to advance dialogue

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#2]
Should be able to click on the dialogue box to advance the conversation if there are no response options (ie: during info dumps) and should be able to click on responses to reply in addition to hitting the number for them.

**Comment by noelmurillo15** [comment]
So, click anywhere on the dialogue box or have a next button in the dialogue box?

**Comment by ClockworkMobius** [comment]
Should be able to click anywhere in the dialogue box if there are no responses.  For example, if the NPC is telling you something that requires more than one screen to display.

**Comment by noelmurillo15** [comment]
Done
