### ISSUE TITLE
Talking to receptionist as first patient arrives breaks the first patient

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#24]
I talked to the receptionist as the first patient was still arriving and requested the patient head to a room, but was told they were all full.  I was unable to get that patient into a room (same message - that the rooms were full).  The next person that arrived allowed me to send that NPC to a room, but the first one just sat there, sadly staring at me, as every patient after him got to go back...but never him.

**Comment by noelmurillo15** [comment]
There is a 1 second delay before the patient moves towards it's waiting room position right after spawning ( for animation to be initialized ). Sending the patient to the patient room before that delay would cause an ovverride as to where the paitent would be sent. Fixed this by stopping the coroutine if the player sends the patient to the patient room as soon as they spawn.
