### ISSUE TITLE
Add test cubes

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#33]
Add cubes and sections to the patient chart for: 

- Chest X-ray PA/Lateral
- Chest CT
- Pulminary Function Test
- CAT Assessment
- Exercise Test
- Arterial blood gas (the results for this can be added to the Blood Test results for now)

If any of the tests in the excel sheet are blank, for now just write "Normal" as the test result.

**Comment by noelmurillo15** [comment]
is functional !
