### ISSUE TITLE
Guideline rooms

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#35]
Guidelines will need to be separated into one of four different rooms, based on the case:

**Heart**:
Atrial Fibrillation
Coronary Artery Disease
Hypertension
Ventricular Arrhythmia

**Lung**:
Asthma
Community Acquired Pneumonia
COPD
Pulmonary Embolism

**GI/Metabolism**:
Colon Cancer Screening
Diabetes Mellitus
Gastroesophageal Reflux Disease
Hyperlipidemia
 
**Other**:
Neurology
Rheumatoid Arthritis
Vaccination

**Comment by noelmurillo15** [comment]
Guidelines are now separated per type
