### ISSUE TITLE
Consolidate blood tests

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#36]
Seems a little silly to have so many different blood tests.  Just have them all come from the one blood test machine - probably too much to ask for the user to run around for five or six different blood tests.

**Comment by noelmurillo15** [comment]
I thought I had all the bloodwork consolidated, what am I missing?
Currently the bloodwork includes CBC, BMP, calcium, arterial gas, d-dimmer, hgb
