### ISSUE TITLE
Quit window stays open if you close and open menu

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#6]
The quit window stays open if you close and then reopen the menu.  This is in the menu only - it successfully hides when leaving the menu back to the playspace.

![image](https://user-images.githubusercontent.com/18316906/89318468-aea5d080-d633-11ea-812e-a21985175dc6.png)

**Comment by noelmurillo15** [comment]
Fixed via Game Resume Event
