### ISSUE TITLE
Patient treatment

### ISSUE THREAD

**Issue by ClockworkMobius** [noelmurillo15/Project-Marmot#8]
Patient vitals, issue descriptions, and treatments will be available via CSV files later.  Past medical history received upon talking to patient and created as a note object you can examine in your inventory.  When patient is treated, the medical history note should be deleted.  Current problem should be discovered via dialogue with patient.

For the disease, use these two for now:

**DISEASE 1**
Past Medical History: 
- Asthma as a child
- Fractured collar bone as a teenager

Current problem:
- Nose is turning green

Treatment:
- Use guideline (from inventory - drag and drop) on patient

**DISEASE 2**
Past Medical History: 
- Chickenpox as a child
- Difficulty breathing through nose

Current problem:
- Constant clucking like a chicken

Treatment:
- Use an object from the environment on patient (generate new item for this - place the object in a different, non-patient room somewhere.  Doesn't matter what it is)

**Comment by noelmurillo15** [comment]
Talking to a patient for the first time will add their past medical history document to your inventory. When a patient is healed, their past medical history document gets discarded from your inventory. A patients' current problem is added to their dialogue queue.

Drag and dropping an object(inventory item) from the environment onto a patient "works" but sometimes the ray-casting while dragging is blocked by something (noticeable when trying this on the patient in the top right room). Having the patient follow you to a different room and trying again usually works.

**Comment by noelmurillo15** [comment]
Writing this comment ^ helped me figure out to just use a LayerMask while ray-casting. Ray-casting works great now.
